export const dateProgramm  = [
    {
        id: 1,
        title: 'Express fit',
        kalls: '800',
        text: 'Healthy eating program Express Fit. Ideal for: losing weight in no time, increasing energy and strength, losing weight with a sedentary lifestyle.',
        name: 'Тестовый день',
        day1: 'at 7 days',
        day2: 'at 14 dasy',
        day3: 'at 30 days',
        food: 'dinner and supper',
        dashed1: 510,
        price1: 367,
        price2: 510,
        price3: 415,
        price4: 200,
        price5: 150,
        price6: 400
    },

    {
        id: 2,
        title: 'slim',
        kalls: '1000',
        text: 'Healthy eating program Express Fit. Ideal for: losing weight in no time, increasing energy and strength, losing weight with a sedentary lifestyle.',
        name: 'Тестовый день',
        day1: 'at 7 days',
        day2: 'at 14 dasy',
        day3: 'at 30 days',
        food: 'dinner and supper',
        dashed1: 510,
        price1: 367,
        price2: 510,
        price3: 415,
        price4: 200,
        price5: 150,
        price6: 400
    },

    {
        id: 3,
        title: 'fitness',
        kalls: '1300',
        text: 'Healthy eating program Express Fit. Ideal for: losing weight in no time, increasing energy and strength, losing weight with a sedentary lifestyle.',
        name: 'Тестовый день',
        day1: 'at 7 days',
        day2: 'at 14 dasy',
        day3: 'at 30 days',
        food: 'dinner and supper',
        dashed1: 510,
        price1: 367,
        price2: 510,
        price3: 415,
        price4: 200,
        price5: 150,
        price6: 400
    },

    {
        id: 4,
        title: 'balance',
        kalls: '1600',
        text: 'Healthy eating program Express Fit. Ideal for: losing weight in no time, increasing energy and strength, losing weight with a sedentary lifestyle.',
        name: 'Тестовый день',
        day1: 'at 7 days',
        day2: 'at 14 dasy',
        day3: 'at 30 days',
        food: 'dinner and supper',
        dashed1: 510,
        price1: 367,
        price2: 510,
        price3: 415,
        price4: 200,
        price5: 150,
        price6: 400
    },

    {
        id: 5,
        title: 'balance +',
        kalls: '1800',
        text: 'Healthy eating program Express Fit. Ideal for: losing weight in no time, increasing energy and strength, losing weight with a sedentary lifestyle.',
        name: 'Тестовый день',
        day1: 'at 7 days',
        day2: 'at 14 dasy',
        day3: 'at 30 days',
        food: 'dinner and supper',
        dashed1: 510,
        price1: 367,
        price2: 510,
        price3: 415,
        price4: 200,
        price5: 150,
        price6: 400
    },

    {
        id: 6,
        title: 'strong',
        kalls: '2000',
        text: 'Healthy eating program Express Fit. Ideal for: losing weight in no time, increasing energy and strength, losing weight with a sedentary lifestyle.',
        name: 'Тестовый день',
        day1: 'at 7 days',
        day2: 'at 14 dasy',
        day3: 'at 30 days',
        food: 'dinner and supper',
        dashed1: 510,
        price1: 367,
        price2: 510,
        price3: 415,
        price4: 200,
        price5: 150,
        price6: 400
    },

    {
        id: 7,
        title: 'maxi fit',
        kalls: '2400',
        text: 'Healthy eating program Express Fit. Ideal for: losing weight in no time, increasing energy and strength, losing weight with a sedentary lifestyle.',
        name: 'Тестовый день',
        day1: 'at 7 days',
        day2: 'at 14 dasy',
        day3: 'at 30 days',
        food: 'dinner and supper',
        dashed1: 510,
        price1: 367,
        price2: 510,
        price3: 415,
        price4: 200,
        price5: 150,
        price6: 400
    }
]