export const food = [
    {
        id: 1,
        food1: 'Breakfast',
        time1: '7:00 - 9:00',
        food2: 'second breakfast',
        time2: '10:00 - 12:00',
        food3: 'Dinner',
        time3: '13:00 - 15:00',
        food4: 'Afternoon tea',
        time4: '16:00 - 17:30',
        food5: 'Supper',
        time6: '19:00 - 20:00',
        menu:  '- Frittata with cheese and zucchini',
        menu1: '- Farm yogurt',
        menu3: ' - Healthy dried fruits and nuts cookies',
        menu4: '- Lula kebab from turkey',
        menu5: '- Summer salad with olives and cheese',
        menu6: '- Cottage cheese soufflé with cocoa and vichy',
        menu7: '- Fish Teren',
        menu8: '- Grilled vegetables',
        gramm1: '170 gr',
        gramm2: '200 gr',
        gramm3: '2 item',
        gramm4: '100gr',
        gramm5: '100gr',
        gramm6: '100gr',
        gramm7: '100gr',
        gramm8: '150gr'
    },

    {
        id: 2,
        food1: 'Breakfast',
        time1: '7:00 - 9:00',
        food2: 'second breakfast',
        time2: '10:00 - 12:00',
        food3: 'Dinner',
        time3: '13:00 - 15:00',
        food4: 'Afternoon tea',
        time4: '16:00 - 17:30',
        food5: 'Supper',
        time6: '19:00 - 20:00',
        menu:  '- Karpasho',
        menu1: '- Panckake',
        menu3: '- Healthy dried fruits and nuts cookies',
        menu4: '- Lula kebab from turkey',
        menu5: '- Summer salad with olives and cheese',
        menu6: '- Cottage cheese soufflé with cocoa and vichy',
        menu7: '- Fish Teren',
        menu8: '- Grilled vegetables',
        gramm1: '120 gr',
        gramm2: '200 gr',
        gramm3: '2 item',
        gramm4: '100gr',
        gramm5: '100gr',
        gramm6: '100gr',
        gramm7: '100gr',
        gramm8: '150gr'
    },

    {
        id: 3,
        food1: 'Breakfast',
        time1: '7:00 - 9:00',
        food2: 'second breakfast',
        time2: '10:00 - 12:00',
        food3: 'Dinner',
        time3: '13:00 - 15:00',
        food4: 'Afternoon tea',
        time4: '16:00 - 17:30',
        food5: 'Supper',
        time6: '19:00 - 20:00',
        menu:  '- Frittata with cheese and zucchini',
        menu1: '- Farm yogurt',
        menu3: ' - Healthy dried fruits and nuts cookies',
        menu4: '- Lula kebab from turkey',
        menu5: '- Summer salad with olives and cheese',
        menu6: '- Cottage cheese soufflé with cocoa and vichy',
        menu7: '- Fish Teren',
        menu8: '- Grilled vegetables',
        gramm1: '170 gr',
        gramm2: '200 gr',
        gramm3: '2 item',
        gramm4: '100gr',
        gramm5: '100gr',
        gramm6: '100gr',
        gramm7: '100gr',
        gramm8: '150gr'
    },

    {
        id: 4,
        food1: 'Breakfast',
        time1: '7:00 - 9:00',
        food2: 'second breakfast',
        time2: '10:00 - 12:00',
        food3: 'Dinner',
        time3: '13:00 - 15:00',
        food4: 'Afternoon tea',
        time4: '16:00 - 17:30',
        food5: 'Supper',
        time6: '19:00 - 20:00',
        menu:  '- Frittata with cheese and zucchini',
        menu1: '- Farm yogurt',
        menu3: ' - Healthy dried fruits and nuts cookies',
        menu4: '- Lula kebab from turkey',
        menu5: '- Summer salad with olives and cheese',
        menu6: '- Cottage cheese soufflé with cocoa and vichy',
        menu7: '- Fish Teren',
        menu8: '- Grilled vegetables',
        gramm1: '170 gr',
        gramm2: '200 gr',
        gramm3: '2 item',
        gramm4: '100gr',
        gramm5: '100gr',
        gramm6: '100gr',
        gramm7: '100gr',
        gramm8: '150gr'
    },

    {
        id: 5,
        food1: 'Breakfast',
        time1: '7:00 - 9:00',
        food2: 'second breakfast',
        time2: '10:00 - 12:00',
        food3: 'Dinner',
        time3: '13:00 - 15:00',
        food4: 'Afternoon tea',
        time4: '16:00 - 17:30',
        food5: 'Supper',
        time6: '19:00 - 20:00',
        menu:  '- Frittata with cheese and zucchini',
        menu1: '- Farm yogurt',
        menu3: ' - Healthy dried fruits and nuts cookies',
        menu4: '- Lula kebab from turkey',
        menu5: '- Summer salad with olives and cheese',
        menu6: '- Cottage cheese soufflé with cocoa and vichy',
        menu7: '- Fish Teren',
        menu8: '- Grilled vegetables',
        gramm1: '170 gr',
        gramm2: '200 gr',
        gramm3: '2 item',
        gramm4: '100gr',
        gramm5: '100gr',
        gramm6: '100gr',
        gramm7: '100gr',
        gramm8: '150gr'
    },

    {
        id: 6,
        food1: 'Breakfast',
        time1: '7:00 - 9:00',
        food2: 'second breakfast',
        time2: '10:00 - 12:00',
        food3: 'Dinner',
        time3: '13:00 - 15:00',
        food4: 'Afternoon tea',
        time4: '16:00 - 17:30',
        food5: 'Supper',
        time6: '19:00 - 20:00',
        menu:  '- Frittata with cheese and zucchini',
        menu1: '- Farm yogurt',
        menu3: ' - Healthy dried fruits and nuts cookies',
        menu4: '- Lula kebab from turkey',
        menu5: '- Summer salad with olives and cheese',
        menu6: '- Cottage cheese soufflé with cocoa and vichy',
        menu7: '- Fish Teren',
        menu8: '- Grilled vegetables',
        gramm1: '170 gr',
        gramm2: '200 gr',
        gramm3: '2 item',
        gramm4: '100gr',
        gramm5: '100gr',
        gramm6: '100gr',
        gramm7: '100gr',
        gramm8: '150gr'
    },

    {
        id: 7,
        food1: 'Breakfast',
        time1: '7:00 - 9:00',
        food2: 'second breakfast',
        time2: '10:00 - 12:00',
        food3: 'Dinner',
        time3: '13:00 - 15:00',
        food4: 'Afternoon tea',
        time4: '16:00 - 17:30',
        food5: 'Supper',
        time6: '19:00 - 20:00',
        menu:  '- Frittata with cheese and zucchini',
        menu1: '- Farm yogurt',
        menu3: ' - Healthy dried fruits and nuts cookies',
        menu4: '- Lula kebab from turkey',
        menu5: '- Summer salad with olives and cheese',
        menu6: '- Cottage cheese soufflé with cocoa and vichy',
        menu7: '- Fish Teren',
        menu8: '- Grilled vegetables',
        gramm1: '170 gr',
        gramm2: '200 gr',
        gramm3: '2 item',
        gramm4: '100gr',
        gramm5: '100gr',
        gramm6: '100gr',
        gramm7: '100gr',
        gramm8: '150gr'
    }
]